# Generates Assets/Icons/IconPaths.xaml: vector PathIcon resources for the toolbar buttons whose
# icon carries a badge (fit on/off, retake, countdown seconds). The outlines are taken from the
# Segoe Fluent Icons / Segoe UI fonts, so they match the other FontIcons, scale with DPI and
# follow the theme through Foreground. Run from the repo root: pwsh Tools/Generate-Icons.ps1

Add-Type -AssemblyName System.Drawing
[System.Threading.Thread]::CurrentThread.CurrentCulture = [System.Globalization.CultureInfo]::InvariantCulture

$outFile = Join-Path $PSScriptRoot "..\Assets\Icons\IconPaths.xaml"
New-Item -ItemType Directory -Force (Split-Path $outFile) | Out-Null

$canvas = 20.0   # logical icon box (DIPs), same as a 20px FontIcon
$format = New-Object System.Drawing.StringFormat([System.Drawing.StringFormat]::GenericTypographic)

function Outline($text, $fontName, $bold) {
    $family = New-Object System.Drawing.FontFamily($fontName)
    $style = if ($bold) { [System.Drawing.FontStyle]::Bold } else { [System.Drawing.FontStyle]::Regular }
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $path.AddString($text, $family, [int]$style, 100.0, (New-Object System.Drawing.PointF 0, 0), $format)
    return $path
}

# Scales/moves a glyph outline so its ink fits inside the given box (keeping aspect), centered in it.
function FitInto($path, $x, $y, $w, $h) {
    $b = $path.GetBounds()
    $scale = [Math]::Min($w / $b.Width, $h / $b.Height)
    $m = New-Object System.Drawing.Drawing2D.Matrix
    $m.Translate($x + ($w - $b.Width * $scale) / 2 - $b.X * $scale, $y + ($h - $b.Height * $scale) / 2 - $b.Y * $scale)
    $m.Scale($scale, $scale, [System.Drawing.Drawing2D.MatrixOrder]::Prepend)
    $path.Transform($m)
}

function ToData($path) {
    $sb = New-Object System.Text.StringBuilder
    $pts = $path.PathPoints; $types = $path.PathTypes
    $i = 0
    while ($i -lt $pts.Length) {
        $t = $types[$i] -band 7
        switch ($t) {
            0 { [void]$sb.Append(("M{0:0.##},{1:0.##} " -f $pts[$i].X, $pts[$i].Y)); $i++ }
            1 { [void]$sb.Append(("L{0:0.##},{1:0.##} " -f $pts[$i].X, $pts[$i].Y)); $i++ }
            3 {
                [void]$sb.Append(("C{0:0.##},{1:0.##} {2:0.##},{3:0.##} {4:0.##},{5:0.##} " -f $pts[$i].X, $pts[$i].Y, $pts[$i+1].X, $pts[$i+1].Y, $pts[$i+2].X, $pts[$i+2].Y))
                $i += 3
            }
            default { $i++ }
        }
        if (($types[$i - 1] -band 0x80) -ne 0) { [void]$sb.Append("Z ") }
    }
    return $sb.ToString().Trim()
}

function Icon($key, $glyph, $badge, $badgeIsGlyph) {
    $main = Outline $glyph "Segoe Fluent Icons" $false
    if ($badge) {
        # Main glyph up-left, badge bottom-right, with clear space between them.
        FitInto $main 0 0 14 14
        $b = if ($badgeIsGlyph) { Outline $badge "Segoe Fluent Icons" $false } else { Outline $badge "Segoe UI" $true }
        $bw = if ($badgeIsGlyph) { 8 } else { 9 }
        FitInto $b ($canvas - $bw) ($canvas - 8) $bw 8
        $main.AddPath($b, $false)
    } else {
        FitInto $main 1 1 18 18
    }
    return "    <x:String x:Key=`"$key`">$(ToData $main)</x:String>"
}

$fit = [string][char]0xE740        # FullScreen (diagonal arrows)
$blocked = [string][char]0xE733    # Blocked
$undo = [string][char]0xE7A7       # Undo
$camera = [string][char]0xE722     # Camera
$stopwatch = [string][char]0xE916  # Stopwatch

$lines = @(
    '<?xml version="1.0" encoding="utf-8" ?>'
    '<!-- Generated by Tools/Generate-Icons.ps1 - do not edit by hand. -->'
    '<ResourceDictionary'
    '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"'
    '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">'
    (Icon "FitOnIcon"        $fit       $null    $false)
    (Icon "FitOffIcon"       $fit       $blocked $true)
    (Icon "RetakeIcon"       $undo      $camera  $true)
    (Icon "CountdownOffIcon" $stopwatch $null    $false)
    (Icon "Countdown3Icon"   $stopwatch "3"      $false)
    (Icon "Countdown5Icon"   $stopwatch "5"      $false)
    (Icon "Countdown10Icon"  $stopwatch "10"     $false)
    '</ResourceDictionary>'
)
[System.IO.File]::WriteAllLines($outFile, $lines, (New-Object System.Text.UTF8Encoding $false))
Write-Host "wrote $outFile"
